u-boot: add PKG_CONFIG_SYSROOT_DIR make flag
On u-boot v2026.04, we need to add PKG_CONFIG_SYSROOT_DIR flag to
fix in-tree dtc tools build without yaml[1-2]. Fixes:

/usr/bin/ld: yamltree.c:(.text+0xa7c): undefined reference to `yaml_sequence_start_event_initialize'
/usr/bin/ld: yamltree.c:(.text+0xa87): undefined reference to `yaml_emitter_emit'
/usr/bin/ld: yamltree.c:(.text+0xaa4): undefined reference to `yaml_sequence_end_event_initialize'
/usr/bin/ld: yamltree.c:(.text+0xaaf): undefined reference to `yaml_emitter_emit'
/usr/bin/ld: yamltree.c:(.text+0xac1): undefined reference to `yaml_document_end_event_initialize'
/usr/bin/ld: yamltree.c:(.text+0xacc): undefined reference to `yaml_emitter_emit'
/usr/bin/ld: yamltree.c:(.text+0xadc): undefined reference to `yaml_stream_end_event_initialize'
/usr/bin/ld: yamltree.c:(.text+0xae7): undefined reference to `yaml_emitter_emit'
/usr/bin/ld: yamltree.c:(.text+0xaf3): undefined reference to `yaml_emitter_delete'

[1] https://github.com/u-boot/u-boot/commit/0535e46d55d7423094d8b553d704a0f7f678de77
[2] https://github.com/u-boot/u-boot/commit/807bcd844afeadbfe47ac132524cc7e3b699bc46
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>